import React from 'react'
import PropTypes from 'prop-types'
import {connect} from 'react-redux'
import {Link} from 'react-router-dom'
import {GoMarkGithub} from 'react-icons/go'
import {AiOutlineLinkedin} from 'react-icons/ai'
